# Generated by Django 5.2.1 on 2025-06-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_id',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user_type',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.university'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.major'),
        ),
    ]
