# Generated by Django 5.2.1 on 2025-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_supervisor_supervisor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
