# Generated by Django 5.2.1 on 2025-06-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
    ]
