# Generated by Django 5.2.1 on 2025-06-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_student_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadDate', models.DateField(auto_created=True)),
                ('ProjectName', models.CharField(max_length=150)),
                ('yearOfProject', models.IntegerField()),
                ('Description', models.TextField()),
                ('rates', models.FloatField()),
                ('MajorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.major')),
                ('UniversityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.university')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('SupervisorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.supervisor')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creativity', models.IntegerField()),
                ('Implementation', models.IntegerField()),
                ('Functionality', models.IntegerField()),
                ('Interface', models.IntegerField()),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.projects')),
                ('SupervisorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.supervisor')),
            ],
        ),
    ]
