# Generated by Django 5.2.1 on 2025-06-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_projects_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
