# Generated by Django 5.2.1 on 2025-06-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_projects_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='media',
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vedio', models.FileField(upload_to='videos/')),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/')),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.projects')),
            ],
        ),
    ]
