# Generated by Django 5.2.1 on 2025-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_projects_media_projectmedia_projectpictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpictures',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
