# Generated by Django 5.2.1 on 2025-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_projectpictures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='FullDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='ProjectType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='PDF/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
