# Generated by Django 5.2.1 on 2025-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_projects_fulldescription_projects_projecttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='rates',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
