# Generated by Django 5.2.1 on 2025-06-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_projects_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='UploadDate',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
