# Generated by Django 5.2.1 on 2025-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_adminuser_alter_projects_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='UploadDate',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
