# Generated by Django 5.2.1 on 2025-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_projects_uploaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
