# Generated by Django 5.2.1 on 2025-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_comments_created_at_ratings_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='UploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
