# Generated by Django 5.2.1 on 2025-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_studentdetails_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
