# Generated by Django 5.2.1 on 2025-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_ratings_notes_alter_skills_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='degree',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
