# Generated by Django 5.2.1 on 2025-06-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_projects_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
