# Generated by Django 5.2.1 on 2025-06-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='classfication',
            field=models.CharField(blank=True, null=True),
        ),
    ]
