# Generated by Django 5.2.1 on 2025-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_projects_classfication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpictures',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
