# Generated by Django 4.2.26 on 2025-11-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_projectpictures_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='classfication',
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
